repos:
  - repo: local
    hooks:
      - id: isort
        stages: [commit]
        name: isort
        language: system
        entry: isort --settings-path api/setup.cfg
        types: [python]
      - id: black
        stages: [commit]
        name: black
        language: system
        entry: black
        types: [python]
      - id: flake8
        stages: [commit]
        name: flake8
        language: system
        entry: flake8 --config api/setup.cfg
        types: [python]
      - id: gitlint
        stages: [commit-msg]
        name: gitlint
        description: Validate commit lint
        entry: gitlint --msg-filename
        language: system
