version: "3"
services:
  db:
    environment:
      - POSTGRES_PASSWORD=mysagw
    ports:
      - "5432:5432"
  api:
    build:
      context: ./api/
      args:
        REQUIREMENTS: requirements-dev.txt
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./api:/app
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000",
      ]
    environment:
      - ENV=dev
