version: "3"
services:
  db:
    environment:
      - POSTGRES_PASSWORD=mysagw
      - CALUMA_DB_PASSWORD=caluma
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
  api:
    build:
      context: ./api/
      args:
        REQUIREMENTS: requirements-dev.txt
    user: "${UID:?Set UID env variable to your user id}"
    volumes:
      - ./api:/app
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000",
      ]
    environment:
      - ENV=dev
  caluma:
    environment:
      - ENV=dev
#      - OIDC_VERIFY_SSL=False
#      - OIDC_USERINFO_ENDPOINT=http://mysagw/openid/userinfo
    volumes:
      - ./caluma/extensions:/app/caluma/extensions:ro
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh db:5432 -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000",
      ]

  ember:
    image: danlynn/ember-cli:latest
    volumes:
      - ./ember:/myapp
      - ./ember/node_modules/:/myapp/node_modules
    tmpfs:
      - /myapp/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
    command: ember serve --proxy http://proxy
