name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UID
        run: echo "UID=$(id --user)" > .env
      - name: Build the containers
        run: docker-compose up -d --build  api db
      - name: Lint the code
        run: make api-lint
      - name: Run test suite
        run: make api-test
  caluma-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UID
        run: echo "UID=$(id --user)" > .env
      - name: Build the containers
        run: docker-compose up -d --build caluma db
      - name: Run test suite
        run: make caluma-test
  caluma-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r ./api/requirements-dev.txt
      - name: Run test suite
        run: make caluma-lint
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install gitlint
        run: pip install gitlint
      - name: Run gitlint
        run: gitlint --contrib contrib-title-conventional-commits --ignore B1,B5,B6
